version: "3.8"

services:
  migrate:
    build: backend
    volumes:
      - ./backend:/srv
    command: python manage.py migrate

  backend:
    build: backend
    volumes:
      - ./backend:/srv
    ports:
      - "8000:8000"
    depends_on: 
      - migrate
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: frontend
    volumes:
      - ./frontend:/srv
      - node_modules:/srv/node_modules
    ports:
      - "1234:8080"
    environment:
     - NODE_ENV="development"

volumes:
  node_modules:
